### ISSUE TITLE
Right-click expands folder in addition to showing context menu

### ISSUE THREAD

**Issue by krassowski** [jupyterlab-contrib/jupyterlab-unfold#26]
## Description

Right-click expands folder in addition to showing context menu

## Reproduce

1. Right click on a folder in the unfold panel
2. See it gets expanded and menu shows up

![right-click](https://user-images.githubusercontent.com/5832902/145678724-72f86082-0d01-49d6-b137-8541e466504b.gif)

## Expected behavior

Only menu shows up

## Context

- Python package version: 0.1.6
- Browser and its version: Chrome

**Comment by krassowski** [comment]
It looks like the logic in:

https://github.com/jupyterlab-contrib/jupyterlab-unfold/blob/be169d39d05c523ff7b322c88a7837ef390b73b9/src/unfold.ts#L351-L358

uses OR where AND should be used. I cannot commit a quick fix it because I do not understand what is the intended behaviour of the logic. @martinRenou do you remember what it was supposed to do? Why is it trying to toggle state on right click ever?

**Comment by martinRenou** [comment]
I am not sure. I would be tempted to only keep this condition:

```typescript
if ( 
   this._singleClickToUnfold && 
   event.button === 0 
)
```

So that we only toggle the directory if the `singleClickToUnfold` config is set and it's a left click. The implementation for dblclick is [here](https://github.com/jupyterlab-contrib/jupyterlab-unfold/blob/master/src/unfold.ts#L210-L219), so it should be enough.

This was introduced by @fcollonval in [this PR](https://github.com/jupyterlab-contrib/jupyterlab-unfold/commit/ebd89cf03da952ba395cd6d4d3c1849efa4d40f2#diff-df130b1810fa2ecd6c783b6cec6b83b76211902c7204615a0d189bf767b620a9R383), maybe you remember why you were doing this?

**Comment by fcollonval** [comment]
:confused: I don't remember why I put that clause. It may be related to the action not taking place on the correct path otherwise.

**Comment by martinRenou** [comment]
If you're ok with it, I opened a PR that reduces the condition to something simpler like suggested above #27
